# Generated by Django 5.2.7 on 2025-11-05 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('General', 'General'), ('Hiring', 'Hiring'), ('Meetup', 'Meetup'), ('Invite', 'Invite')], default='General', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meetup_time', models.DateTimeField(blank=True, null=True)),
                ('meetup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
